### ISSUE TITLE
getting fetch API and svelte error when attempting to chat

### ISSUE THREAD

**Issue by fitsum** [aetaix/ollami#4]
I get the following errors when I try to enter a chat 

```
Error: Error: Cannot use relative URL (/api/chat) with global fetch — use `event.fetch` instead: https://kit.svelte.dev/docs/web-standards#fetch-apis                                                                                         
    at globalThis.fetch (file:///Users/fitsum010/Documents/Node/review/llm/ollami/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:44:10)                                                                                             
    at postToApi (/Users/fitsum010/Documents/Node/review/llm/ollami/node_modules/ollama-ai-provider/node_modules/@ai-sdk/provider-utils/dist/index.js:249:28)                                                                                 
    at postJsonToApi (/Users/fitsum010/Documents/Node/review/llm/ollami/node_modules/ollama-ai-provider/node_modules/@ai-sdk/provider-utils/dist/index.js:223:7)                                                                              
    at OllamaChatLanguageModel.doStream (/Users/fitsum010/Documents/Node/review/llm/ollami/node_modules/ollama-ai-provider/dist/index.js:382:97)                                                                                              
    at eval (/Users/fitsum010/Documents/Node/review/llm/ollami/node_modules/ai/dist/index.mjs:1394:17)
    at _retryWithExponentialBackoff (/Users/fitsum010/Documents/Node/review/llm/ollami/node_modules/ai/dist/index.mjs:330:18)
    at eval (/Users/fitsum010/Documents/Node/review/llm/ollami/node_modules/ai/dist/index.mjs:319:25)
    at Module.streamText (/Users/fitsum010/Documents/Node/review/llm/ollami/node_modules/ai/dist/index.mjs:1393:51)
    at POST (/Users/fitsum010/Documents/Node/review/llm/ollami/src/routes/api/chat/+server.ts:25:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Invalid response from route /api/chat: handler should return a Response object
    at Module.render_endpoint (/Users/fitsum010/Documents/Node/review/llm/ollami/node_modules/@sveltejs/kit/src/runtime/server/endpoint.js:48:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolve (/Users/fitsum010/Documents/Node/review/llm/ollami/node_modules/@sveltejs/kit/src/runtime/server/respond.js:443:17)
    at async Module.respond (/Users/fitsum010/Documents/Node/review/llm/ollami/node_modules/@sveltejs/kit/src/runtime/server/respond.js:319:20)
    at async file:///Users/fitsum010/Documents/Node/review/llm/ollami/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:524:22
```

**Comment by solazio** [comment]
same for me

**Comment by BalkanCloud** [comment]
Not working!
